### ISSUE TITLE
Will this work on IOS in a flutter browser?

### ISSUE THREAD

**Issue by samjco** [Merve40/ptt#3]
Will this work on IOS in a flutter browser?

**Comment by Merve40** [comment]
I do not think it will work, as the web-browsers on iOS do not allow access to the microphone. I think [flutter](https://flutter.dev/web) uses the underlying web-view/browser of iOS:  `Adding web support to Flutter involved implementing Flutter’s core drawing layer on top of standard browser APIs.`

**Comment by samjco** [comment]
Will something like this work using Flutter?:
https://pub.dev/packages/flutter_webrtc
https://pub.dev/packages/speech_recognition
https://pub.dev/packages/flutter_speech

**Comment by Merve40** [comment]
My implementation is based on websockets, not webrtc. If you want to use any of these APIs you need to implement it yourself. Webrtc might work but I don't know if it can handle hundreds of simultaneous peer connections.
