### ISSUE TITLE
Ejecución segundo plano

### ISSUE THREAD

**Issue by Alozada88** [Merve40/ptt#8]
Execution stops in the phone's browser when the screen locks, Is it possible to keep running even if the phone is locked?

**Comment by Merve40** [comment]
Unfortunately this is not possible. The browser is a sandbox so the website cannot influence the behaviour of the phone. If you are using android you can use the native implementation of the android app here:  https://github.com/Merve40/ptt-android

**Comment by Alozada88** [comment]
Oh thank you!! i'll try the android app.

i'm sorry in the future i'll  use just  english in my asks.
